"""
main.py — LGA Map API
Serves pre-generated SVG path data for Nigerian states.
Each state is stored as data/{state-slug}.json generated by geo.py.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import importlib
import pkgutil
import routers



app = FastAPI(
    title="Nigeria LGA Map API",
    description="SVG path data for all Nigerian LGAs, projected and ready to render.",
    version="2.0.0",
    redirect_slashes=False,
)

for loader, module_name, is_pkg in pkgutil.iter_modules(routers.__path__):

    # 1. Import the file
    module = importlib.import_module(f"routers.{module_name}")

    # 2. Look for the 'route' or 'router' variable inside that file
    router = getattr(module, "route", getattr(module, "router", None))

    if router:
        # 3. Include it automatically
        app.include_router(router)

ALLOWED_ORIGINS = [
    "https://clarion.tasguard.com",
    "https://clarioncall.tasguard.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=False,
    allow_methods=["GET", "OPTIONS"],
    allow_headers=["*"],
)


@app.get("/health")
def health():
    return {"message": "Welcome to Ucircle", "status": "ok"}