"""
main.py — LGA Map API
Serves pre-generated SVG path data for Nigerian states.
Each state is stored as data/{state-slug}.json generated by geo.py.
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import json
from pathlib import Path

from routers import geo



app = FastAPI(
    title="Nigeria LGA Map API",
    description="SVG path data for all Nigerian LGAs, projected and ready to render.",
    version="2.0.0",
    redirect_slashes=False,
)

app.include_router(geo.route)

ALLOWED_ORIGINS = [
    "https://clarion.tasguard.com",
    "https://clarioncall.tasguard.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=False,
    allow_methods=["GET", "OPTIONS"],
    allow_headers=["*"],
)

DATA_DIR = Path("data")


@app.get("/health")
def health():
    return {"message": "Welcome to Ucircle", "status": "ok"}