"""
main.py — LGA Map API
Serves pre-generated SVG path data for Nigerian states.
Each state is stored as data/{state-slug}.json generated by generate.py.
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import json
from pathlib import Path

app = FastAPI(
    title="Nigeria LGA Map API",
    description="SVG path data for all Nigerian LGAs, projected and ready to render.",
    version="2.0.0",
)

ALLOWED_ORIGINS = [
    "https://clarion.tasguard.com",
    "https://clarioncall.tasguard.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=False,
    allow_methods=["GET", "OPTIONS"],
    allow_headers=["*"],
)

DATA_DIR = Path("data")


def _available_states() -> list[str]:
    """Return all state slugs that have a generated JSON file."""
    return sorted(
        p.stem for p in DATA_DIR.glob("*.json")
        if not p.stem.startswith("_")  # exclude _geojson_cache
    )


def _load_state(slug: str) -> dict:
    path = DATA_DIR / f"{slug}.json"
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"State '{slug}' not found. Available: {_available_states()}",
        )
    return json.loads(path.read_text(encoding="utf-8"))


@app.on_event("startup")
def on_startup():
    states = _available_states()
    if not states:
        print("⚠️  No state files found in data/. Run generate.py first.")
    else:
        print(f"✅ Ready — {len(states)} state(s) available: {', '.join(states[:5])}{'…' if len(states) > 5 else ''}")


@app.get("/")
def root():
    states = _available_states()
    return {
        "service": "Nigeria LGA Map API",
        "states_available": len(states),
        "endpoints": ["/states", "/lgas/{state}", "/lgas/{state}/with-ratings"],
    }


@app.get("/health")
def health():
    return {"status": "ok", "states": len(_available_states())}


@app.get("/states")
def list_states():
    """List all available state slugs."""
    return {"states": _available_states()}


@app.get("/lgas/{state}")
def get_lgas(state: str):
    """
    Get SVG path data for all LGAs in a state.
    Returns viewbox string and list of LGA shapes.

    Example: GET /lgas/lagos
    """
    return _load_state(state.lower().strip().replace(" ", "-"))


@app.get("/lgas/{state}/with-ratings")
def get_lgas_with_ratings(state: str):
    """
    Get LGA shapes merged with live ratings.
    Currently returns shape data only — ratings merge coming soon.
    """
    state_data = _load_state(state.lower().strip().replace(" ", "-"))

    # TODO: query your Railway Postgres ratings table and merge in here
    lgas_with_ratings = [
        {
            **lga,
            "rating": None,
            "reviews_count": 0,
            "lgi_name": None,
        }
        for lga in state_data["lgas"]
    ]

    return {
        "viewbox": state_data["viewbox"],
        "lgas": lgas_with_ratings,
    }