"""
main.py — LGA Map API
Serves pre-generated SVG path data for Nigerian states.
Each state is stored as data/{state-slug}.json generated by geo.py.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import importlib
import pkgutil
import routers



app = FastAPI(
    title="Nigeria Map API",
    description="SVG path data for all Nigerian Map, projected and ready to render.",
    version="2.0.0",
    redirect_slashes=False,
)

for loader, module_name, is_pkg in pkgutil.iter_modules(routers.__path__):

    # 1. Import the file
    module = importlib.import_module(f"routers.{module_name}")

    # 2. Look for the 'route' or 'router' variable inside that file
    router = getattr(module, "route", getattr(module, "router", None))

    if router:
        # 3. Include it automatically
        app.include_router(router)

ALLOWED_ORIGINS = [
    "https://datalorry.com",
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    "http://localhost:5173",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "OPTIONS", "PUT", "DELETE"],
    allow_headers=["*"],
)

from database import engine, Base
import models

@app.on_event("startup")
def on_startup():
    print("🚀 Auto-migrating and ensuring database tables exist...")
    # This creates any tables that do not exist based on models.py
    Base.metadata.create_all(bind=engine)
    print("✅ Database tables ensured.")


@app.get("/health")
def health():
    return {"message": "Welcome to DataLorry", "status": "ok"}